### ISSUE TITLE
About training

### ISSUE THREAD

**Issue by ZUGE0312** [ShawnDong98/DERNN-LNLT#1]
请问您在跑实验过程中遇到过 loss为nan的情况吗，我这里使用共享参数跑实验的话经常会loss为nan，不共享参数会稍微好一些？

**Comment by ShawnDong98** [comment]
你有修改配置吗？RNN 会比较容易梯度爆炸，代码里默认有梯度裁剪。我没有遇到过 loss 为 nan 的情况。

**Comment by MiaBakhtiyar** [comment]
> 请问您在跑实验过程中遇到过 loss为nan的情况吗，我这里使用共享参数跑实验的话经常会loss为nan，不共享参数会稍微好一些？

请问你的问题解决了吗，我现在也是训练过程中model_out出现NaN
