### ISSUE TITLE
Image size of visulization

### ISSUE THREAD

**Issue by Johnweii25** [ShawnDong98/DERNN-LNLT#4]
Hi,after using visulize simulation results,the size of reconstructions are 439x440,it's a little different from MST-L and other previous works,then how you evaluate the results with them?Resize all?

**Comment by ShawnDong98** [comment]
The visualized images from the MST repository will have a white border. To maintain consistent size, you can directly use the code from the MST repository for visualization, as it is fully compatible.

**Comment by Johnweii25** [comment]
thanks

**Comment by Johnweii25** [comment]
> The visualized images from the MST repository will have a white border. To maintain consistent size, you can directly use the code from the MST repository for visualization, as it is fully compatible.

Hi, great work! i got confused on show ground truth in your matlab code,there isn't exist any truth.mat for visualization,can u upload them or email me(douww0730@163.com)?
